export const REQUIRED_BUNDLED_SKILL_IDS = Object.freeze(["create-skill"]);

export const KNOWN_M0_TOOL_NAMES = Object.freeze([
  "read_file",
  "list_files",
  "search_text",
  "write_file",
  "edit_file",
  "text_stats",
  "edit_text_range",
  "batch_edit_text",
  "compare_text",
  "normalize_text",
  "extract_text",
  "split_text",
  "validate_text",
  "replace_text",
  "transform_lines",
  "merge_text",
  "inspect_text",
  "analyze_text_structure",
  "ranked_search_text",
  "find_similar_text",
  "select_text_context",
  "delegate_task",
  "create_skill",
  "get_narrative_outline",
  "get_chapter_outline_context",
  "list_narrative_promises",
  "check_narrative_outline",
  "propose_outline_patch",
  "apply_outline_patch",
  "map_outline_nodes_to_chapter",
  "generate_book_chapter_content",
]);
